### ISSUE TITLE
App.jsx에서의 컴포넌트에 대하여...

### ISSUE THREAD

**Issue by helloworld442** [khu107/to_do#1]
App.jsx에서 TodolistItem같은 경우에는 반복되는 경우가 많은데 반복되는 경우들을 따로 컴포넌트로 분리시키는 것은 어떨까요?
따로 컴포넌트 분리 없이 App.jsx에 한번에 모든 로직을 처리하신 이유가 있을까요???
App.jsx에서 삭제,완료 로직이 아주 깔끔한 것 같습니다!

**Comment by khu107** [comment]
수정 완성!!!
